### ISSUE TITLE
[request] about enhance sbcl ext:atomic-incf

### ISSUE THREAD

**Issue by ukari** [Shinmera/atomics#2]
#### (symbol-value ...)
In sbcl, `ext:atomic-update` could receive a `(symbol-value ...)` as its `place` arguement, while `ext:atomic-incf` or `ext:atomic-decf` not support that.

``` lisp
(defparameter a 0)
(sb-ext:atomic-update (symbol-value 'a)
                      (lambda (place) (setf (symbol-value 'place) (+ place 1)))) ;; it works
(sb-ext:atomic-incf (symbol-value a)) ;; not works
```
If use `ext:atomic-update` to implement `atomics:atomic-incf` for `#+sbcl` instead of directly use `ext:atomic-incf`, it will inherit the benefit of accept `(symbol-value ...)` .

#### "raw" symbol
Additionally, the "raw" symbol is treated similar to `symbol-value` in sbcl.

``` lisp
(defparameter a 0)

(defmacro atomic-incf-foo (place &optional (delta 1))
  `(sb-ext:atomic-update ,place (lambda (,place) (setf ,place (+ ,place ,delta)))))

(atomic-incf-foo a)
```

### ecl
The situation might be same in the ecl, I haven't test it in ecl because my ecl don't have a `mp:compare-and-swap`, but here is a [ref](https://gitlab.com/embeddable-common-lisp/ecl/issues/460)

**Comment by Shinmera** [comment]
Atomics is a thin wrapper over what the implementation provides. It already exposes `atomic-update`, so you can simply write a wrapper around that and use it in your code, if the semantics of doing so are fine for your purposes.

I would rather avoid emulating behaviour of the exposed operators with others. For instance, `atomic-incf` is most likely implemented through `XADD`, while `atomic-update` is most likely using `CMPXCHG`. These are two different instructions with different semantics.
