### ISSUE TITLE
ECL supports cas and atomic-incf on special variables

### ISSUE THREAD

**Issue by Plisp** [Shinmera/atomics#7]
See https://gitlab.com/embeddable-common-lisp/ecl/-/issues/460.

I also tested atomic-incf on x64 linux with the following which appears to give the desired result:
```lisp
(defvar *xxx* 0)
(loop for thread in (loop for i from 1 to 100
                          collect (bt:make-thread 
                                   (lambda () 
                                     (loop repeat 1000000
                                           do (mp:atomic-incf *xxx*)))))
      do (bt:join-thread thread)
      finally (print *xxx*))
```
Support can be confirmed https://gitlab.com/embeddable-common-lisp/ecl/-/blob/develop/src/lsp/mp.lsp#L386.

**Comment by Shinmera** [comment]
Thanks for the heads-up!
